# Generated by Django 4.1.2 on 2022-10-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='intractive_map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, null=True)),
                ('Phoneno', models.CharField(max_length=255, null=True)),
                ('UnitNo', models.IntegerField(null=True)),
                ('UnitNo_primary', models.IntegerField(null=True)),
                ('BlockNo', models.CharField(max_length=255, null=True)),
                ('UnitArea', models.CharField(max_length=255, null=True)),
                ('LandArea', models.CharField(max_length=255, null=True)),
                ('UType', models.CharField(max_length=255, null=True)),
                ('Price', models.FloatField(null=True)),
                ('Bank', models.CharField(max_length=255, null=True)),
                ('Status', models.CharField(max_length=255, null=True)),
                ('dt', models.DateField(auto_now_add=True)),
                ('tm', models.TimeField(auto_now_add=True)),
                ('current_status', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
