# Generated by Django 4.1.2 on 2022-10-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intractive_map',
            name='attached_file',
            field=models.FileField(null=True, upload_to='property_image'),
        ),
    ]
