# Generated by Django 4.1.2 on 2022-11-28 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0002_plot_view_master_plot_view_master_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(auto_now=True)),
                ('tm', models.TimeField(auto_now=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=255, null=True)),
                ('fname', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer_details',
            name='customer_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intractive_map',
            name='customer_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_request_plot',
            name='customer_email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
