# Generated by Django 4.1.2 on 2022-10-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0003_user_details_user_manger_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='atatchment',
            field=models.FileField(null=True, upload_to='user_image'),
        ),
    ]
