# Generated by Django 4.1.2 on 2022-10-31 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0006_user_request_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_request_plot',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_request_plot_manager_id', to='super_admin.user_details'),
        ),
    ]
