# Generated by Django 4.1.2 on 2022-10-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0007_user_request_plot_manager_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_request_plot',
            name='read_status',
            field=models.IntegerField(default=0),
        ),
    ]
