# Generated by Django 4.1.2 on 2022-11-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0008_user_request_plot_read_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_request_plot',
            name='booking_status',
            field=models.IntegerField(null=True),
        ),
    ]
