# Generated by Django 4.1.2 on 2022-11-01 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0009_user_request_plot_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='intractive_map_multiple_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_file', models.FileField(null=True, upload_to='property_multiple_image')),
                ('image_type', models.CharField(max_length=255, null=True)),
                ('dt', models.DateField(auto_now_add=True)),
                ('tm', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('mapping_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intractive_map_multiple_image_id', to='super_admin.intractive_map')),
            ],
        ),
    ]
