# Generated by Django 4.1.2 on 2022-11-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0011_intractive_map_multiple_image_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='plot_list_view',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
