# Generated by Django 4.1.2 on 2022-11-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0012_user_details_plot_list_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='intractive_map',
            name='currency',
            field=models.CharField(default='SAR', max_length=255, null=True),
        ),
    ]
