# Generated by Django 4.1.2 on 2022-11-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0014_intractive_map_price_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intractive_map',
            name='price_visibility',
        ),
        migrations.AddField(
            model_name='user_details',
            name='price_visibility',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
