# Generated by Django 4.1.2 on 2022-11-03 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('super_admin', '0015_remove_intractive_map_price_visibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(auto_now=True)),
                ('tm', models.TimeField(auto_now=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=255, null=True)),
                ('user_type', models.CharField(choices=[('administrator', 'administrator'), ('staff', 'staff')], max_length=255, null=True)),
                ('d_text', models.TextField(null=True)),
                ('action_appy_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_log_user_login_id', to='super_admin.user_details')),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_log_auth_login_id', to=settings.AUTH_USER_MODEL)),
                ('booking_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_log_id', to='super_admin.user_request_plot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
