# Generated by Django 4.1.2 on 2022-11-03 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0016_booking_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_log',
            name='assigned_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_log_assign_user_login_id', to='super_admin.user_details'),
        ),
    ]
