# Generated by Django 4.1.2 on 2022-11-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0017_booking_log_assigned_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_log',
            name='log_type',
            field=models.CharField(choices=[('administrator', 'administrator'), ('staff', 'staff')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking_log',
            name='status_content',
            field=models.TextField(null=True),
        ),
    ]
