# Generated by Django 4.1.2 on 2022-11-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0018_booking_log_log_type_booking_log_status_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='property_access',
            field=models.CharField(choices=[('all', 'all'), ('plot_based', 'plot_based')], max_length=255, null=True),
        ),
    ]
