# Generated by Django 4.1.2 on 2022-11-03 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('super_admin', '0019_user_details_property_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_access_property_mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(auto_now=True)),
                ('tm', models.TimeField(auto_now=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=255, null=True)),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_access_property_mapping_auth_id', to=settings.AUTH_USER_MODEL)),
                ('mapping_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_access_property_mapping_id', to=settings.AUTH_USER_MODEL)),
                ('property_mapping_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_access_property_mapping_property_id', to='super_admin.intractive_map')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
