# Generated by Django 4.1.2 on 2022-11-03 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0020_user_access_property_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_access_property_mapping',
            name='mapping_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_access_property_mapping_id', to='super_admin.user_details'),
        ),
    ]
