# Generated by Django 4.1.2 on 2022-11-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0023_user_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_log',
            name='user_type',
            field=models.CharField(choices=[('administrator', 'administrator'), ('staff', 'staff')], max_length=255, null=True),
        ),
    ]
