# Generated by Django 4.1.2 on 2022-11-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0024_user_log_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intractive_map',
            name='LandArea',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='intractive_map',
            name='UnitArea',
            field=models.FloatField(max_length=255, null=True),
        ),
    ]
