# Generated by Django 4.1.2 on 2022-11-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0025_alter_intractive_map_landarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intractive_map',
            name='Price',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
    ]
