# Generated by Django 4.1.2 on 2022-11-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0036_alter_intractive_map_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='intractive_map',
            name='Price_currency',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
