# Generated by Django 4.1.2 on 2022-11-09 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0037_intractive_map_price_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='status_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(auto_now=True)),
                ('tm', models.TimeField(auto_now=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=255, null=True)),
                ('text', models.CharField(choices=[('administrator', 'administrator'), ('staff', 'staff')], max_length=255, null=True)),
                ('status_code', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
