# Generated by Django 4.1.2 on 2022-11-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0038_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_code',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
