# Generated by Django 4.1.2 on 2022-11-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0039_alter_status_code_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='manager_nav_ploat_permission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_details',
            name='manager_nav_plot_edit_permission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_details',
            name='manager_nav_user_permission',
            field=models.IntegerField(default=0),
        ),
    ]
