# Generated by Django 4.1.2 on 2022-11-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0042_intractive_map_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_request_plot',
            name='available_status',
            field=models.IntegerField(default=1),
        ),
    ]
