# Generated by Django 4.1.2 on 2022-11-10 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('super_admin', '0043_user_request_plot_available_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customer_details_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
