# Generated by Django 4.1.2 on 2022-11-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0044_customer_details_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='conduct_certi',
            field=models.FileField(null=True, upload_to='customer_document'),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='customer_doc_id',
            field=models.FileField(null=True, upload_to='customer_document'),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'individual'), ('company', 'company')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='satte',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='street1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='street2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='tax_certificate',
            field=models.FileField(null=True, upload_to='customer_document'),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='zip',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
