# Generated by Django 4.1.2 on 2022-11-11 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0046_bank_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='bank_relation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customer_details_Bank_details_id', to='super_admin.bank_details'),
        ),
        migrations.AddField(
            model_name='user_request_plot',
            name='bank_relation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_request_plot_Bank_details_id', to='super_admin.bank_details'),
        ),
    ]
