# Generated by Django 4.1.2 on 2022-11-11 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0047_customer_details_bank_relation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_details',
            old_name='conduct_certi',
            new_name='contract_certi',
        ),
    ]
