# Generated by Django 4.1.2 on 2022-11-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0048_rename_conduct_certi_customer_details_contract_certi'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='other_document',
            field=models.FileField(null=True, upload_to='customer_document'),
        ),
        migrations.AddField(
            model_name='user_request_plot',
            name='contract_certi',
            field=models.FileField(null=True, upload_to='customer_document'),
        ),
        migrations.AddField(
            model_name='user_request_plot',
            name='customer_doc_id',
            field=models.FileField(null=True, upload_to='customer_document'),
        ),
        migrations.AddField(
            model_name='user_request_plot',
            name='other_document',
            field=models.FileField(null=True, upload_to='customer_document'),
        ),
        migrations.AddField(
            model_name='user_request_plot',
            name='tax_certificate',
            field=models.FileField(null=True, upload_to='customer_document'),
        ),
    ]
