# Generated by Django 4.1.2 on 2022-11-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0049_customer_details_other_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='customer_document'),
        ),
    ]
