# Generated by Django 4.1.2 on 2022-11-12 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0050_customer_details_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='intractive_map',
            name='bank_relation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intractive_map_Bank_details_id', to='super_admin.bank_details'),
        ),
    ]
