# Generated by Django 4.1.2 on 2022-11-12 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0051_intractive_map_bank_relation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='intractive_map',
            name='customer_id_mapping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intractive_map_customer_id', to='super_admin.customer_details'),
        ),
    ]
