# Generated by Django 4.1.2 on 2022-11-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0052_intractive_map_customer_id_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='user_type',
            field=models.CharField(choices=[('manager', 'manager'), ('salesman', 'salesman'), ('admin', 'admin')], max_length=255, null=True),
        ),
    ]
