# Generated by Django 4.1.2 on 2022-11-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0054_user_request_plot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='contract_certi_extesion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='contract_certi_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='contract_certi_update_dt',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='customer_doc_id_extesion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='customer_doc_id_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='customer_doc_id_update_dt',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='other_document_extesion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='other_document_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='other_document_update_dt',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='tax_certificate_extesion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='tax_certificate_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='tax_certificate_update_dt',
            field=models.DateField(null=True),
        ),
    ]
