# Generated by Django 4.1.2 on 2022-11-16 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0055_customer_details_contract_certi_extesion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_log',
            name='intractive_map_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_log_intractive_map_id_id', to='super_admin.user_request_plot'),
        ),
    ]
