# Generated by Django 4.1.2 on 2022-11-16 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0056_booking_log_intractive_map_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_log',
            name='intractive_map_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_log_intractive_map_id_id', to='super_admin.intractive_map'),
        ),
    ]
