# Generated by Django 4.1.2 on 2022-11-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0057_alter_booking_log_intractive_map_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='manager_nav_booking_cancel_permission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_details',
            name='manager_nav_customer_edit_permission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_details',
            name='manager_nav_customer_read_permission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_details',
            name='manager_nav_customer_write_permission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_details',
            name='manager_nav_document_edit_permission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_details',
            name='manager_nav_document_read_permission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_details',
            name='manager_nav_document_write_permission',
            field=models.IntegerField(default=0),
        ),
    ]
