# Generated by Django 4.1.2 on 2022-11-17 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0058_user_details_manager_nav_booking_cancel_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intractive_map',
            name='customer_id_mapping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intractive_map_customer_id', to='super_admin.customer_details'),
        ),
    ]
